# Ref here for more compactable version: https://hub.docker.com/r/qdrant/qdrant/tags
# Ref here for connection setup : https://qdrant.tech/documentation/quickstart/

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network

volumes:
  qdrant_storage:
    name: qdrant_storage
    driver: local

networks:
  app-network:
    name: app-network
    driver: bridge