# version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:17.7.0-ce.0
    container_name: gitlab
    restart: always
    # hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        # external_url 'https://gitlab.example.com'
    ports:
      - '8088:80'
      # - '443:443'
      # - '22:22'
    volumes:
      - config:/etc/gitlab'
      - logs:/var/log/gitlab'
      - data:/var/opt/gitlab'
    shm_size: '256m'

volumes:
  config:
    driver: local
  logs:
    driver: local
  data:
    driver: local
    