# version: '3.8'
services:
  jenkins-master:
    container_name: jenkins-master
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "./jenkins_home:/var/jenkins_home"
