services:
  jenkins-master:
    container_name: jenkins-master
    build:
      context: ./master
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./jenkins_home:/var/jenkins_home"
  jenkins-agent:
    container_name: jenkins-agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    restart: always
    env_file: ".env"
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=${JENKINS_SECRET} 
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME} 
    depends_on:
      - jenkins-master