# version: '3.8'
services:
  registry:
    image: registry:2
    container_name: registry
    # ports:
    #   - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      # - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./certs:/etc/nginx/certs:ro
    depends_on:
      - registry

volumes:
  registry_data:
