# version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - "./mysql_data:/var/lib/mysql"
    restart: on-failure
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin_web:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: on-failure
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - './phpmyadmin_config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php'
    environment:
      PMA_HOST: ${PMA_HOST}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
