version: '3.8'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      # - KAFKA_CREATE_TOPICS=python-sample:1:1
      - KAFKA_CREATE_TOPICS=topic-sample-one:1:1,topic-sample-two:2:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
