# version: '3.8'
services:
  redis:
    image: redis:7.4-bookworm
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--appendonly", "yes"]
    mem_limit: 512m # Limiting memory usage

  redis-streams:
    image: redis:alpine
    container_name: redis-streams
    ports:
      - "6378:6379"
    networks:
      - app-network

volumes:
  redis_data:
    driver: local
